- import_playbook: "set_variables.yml"

- name: Create a new database with name 'prueba'
  mysql_db:
    name: prueba
    login_host: dnsserver1.eastonlab.org
    login_user: ambari
    login_password: bigdata
    state: present
